config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :attendances
    resources :events
    resources :user_events
    resources :preregistrations

    root to: 'users#index'
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # HighVoltage
  get '/dashboard' => 'dashboards#index', id: 'dashboard'
  get '/pages/user_manual' => 'pages#user_manual'

  resources :users, only: %i(edit update)
  resources :events, only: %i(new create show edit update destroy) do
    resources :attendances, only: %i(create index destroy) do
      collection do
        get 'export'
      end
    end
    resources :user_events, only: %i(create destroy)
    resources :preregistrations, only: %i(index new create destroy) do
      collection { post 'import' }
    end
  end
  resources :lookups, only: %i(index create)

  get '/heartbeat' => 'heartbeat#show'
  get '/heartbeat/api' => 'heartbeat#api'

  root to: 'pages#home', id: 'home'
end

app/models/event.rb
# frozen_string_literal: true

# Class for Cardswipr events
# @attr Title [String] Title of the event being made.
# @attr Description [String] Describes the event being made
class Event < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }

  before_validation :remove_whitespaces

  # Associations
  has_many :attendances, dependent: :destroy
  has_many :user_events, dependent: :destroy
  has_many :users, through: :user_events
  has_many :preregistrations, dependent: :destroy
  has_many :check_ins, dependent: :destroy

  private

  def remove_whitespaces
    title.strip! if title.present?
    description.strip! if description.present?
  end
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

module Admin
  class EventsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions
    # to implement custom behavior.
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/events_controller.rb
module Api
  class EventsController < ApplicationController
    protect_from_forgery with: :null_session
    respond_to :json
    load_and_authorize_resource param_method: :event_params

    # POST /api/{plural_resource_name}
    def create
      if @event.save
        render :show, status: :created
      else
        render json: event.errors, status: :unprocessable_entity
      end
    end

    # DELETE /api/{plural_resource_name}/1
    def destroy
      @event.destroy
      head :no_content
    end

    # GET /api/{plural_resource_name}
    def index
      respond_with @events.to_json
    end

    # GET /api/{plural_resource_name}/1
    def show
      respond_with @event.to_json
    end

    # PATCH/PUT /api/{plural_resource_name}/1
    def update
      if @event.update(event_params)
        render :show
      else
        render json: @event.errors, status: :unprocessable_entity
      end
    end


    private

      def event_params
        params.require(:event).permit(:title)
      end

      # def query_params
      #   # this assumes that an album belongs to an artist and has an :artist_id
      #   # allowing us to filter by this
      #   params.permit(:event_id, :title)
      # end

  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# Events Controller
class EventsController < ApplicationController
  prepend_before_action :set_event, only: %i(show edit update destroy)
  before_action :set_user_events, only: %i(edit update)
  layout 'application_without_nav_or_footer', only: %i(show)

  def new
    @event = Event.new
  end

  def create
    obj = EventCreator.new(params: event_params, owner: current_user)
    if obj.call
      redirect_to event_attendances_path(obj.event),
                  notice: 'Successfully created event!'
    else
      @event = obj.event
      flash_alerts(obj)
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to edit_event_path(@event.id), notice: 'Event Updated'
    else
      flash_alerts(@event)
      render 'edit', event: @event.id
    end
  end

  def destroy
    @event.destroy
    redirect_to dashboard_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def set_user_events
    @user_event = UserEvent.new
    @user_events = @event.user_events
                         .joins(:user).order(Arel.sql('lower(last_name)'))
  end

  def event_params
    params.require(:event).permit(:title, :description, :preregistration)
  end

  def authorize!
    if @event
      authorize(@event)
    else
      authorize Event.new
    end
  end
end

app/views/events/_form.html.erb
<div class = "col-md-10">
  <%= simple_form_for @event do |f| %>
    <%= f.label 'Title', class: 'label-required' %>
    <%= f.input :title, label: false, error: '', input_html: { class: 'form-control', 'aria-describedby' => 'titleHelp' } %>
    <p><small id='titleHelp'>This will be displayed on the swipe-in screen in large text.</small></p>
    <%= f.label 'Description' %>
    <%= f.input :description, label: false, error: '', input_html: { class: 'form-control', 'aria-describedby' => 'descriptHelp' } %>
    <p><small id='descriptHelp'>This will be displayed on the swipe-in screen in smaller text. You might tell attendees how you will use their email or NetID, or what they should do after swiping in.</small></p>
    <%= f.label 'Require Preregistrations' %>
    <%= f.input :preregistration, type: 'checkbox', error: '', label: false, input_html: { 'aria-describedby' => 'preregHelp' } %>
    <p><small id='preregHelp'>Allow event managers to upload a list of preregistered attendees. Only preregistered attendees will be able to check in to this event.</small></p>
    <%= f.submit class: "btn btn-yale" %>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class = "text-center">
  <h1>Edit Event: <%= @event.title %></h1>
</div>

<div class = "container">
  <%= render 'events/form' %>
  <br/>

  <% if @event.preregistration %>
    <h3>Preregistrations</h3>
    <div class="container" id="add-preregistrations">
      <%= button_to 'Add Preregistrations', new_event_preregistration_path(@event.id), method: :get, :class => 'btn btn-primary' %>
    </div>
  <% end %>

  <div id='user-event-form'>
    <h3>Event Organizers</h3>
      <div class="container">
        <table aria-label="Event Organizers" class="event-organizers-table col-md-6">
          <thead>
            <tr>
              <th scope = "col">Name</th>
              <th scope = "col">NetId</th>
              <th scope = "col"></th>
            </tr>
          </thead>
          <tbody>
            <% @user_events.each do |user_event| %>
              <tr id= "remove-<%= user_event.user.username %>">
                <th scope = "row" data-role="Full Name"><%= user_event.user.full_name %></th>
                <td data-role = "NetId"><%= user_event.user.username %></td>
                <td data-role = "Remove Organizer">
                  <%= link_to 'X', event_user_event_path(user_event.event, user_event, user_event.id),
                  method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger with-border", aria: { label: 'Remove Organizer' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div>
          <%= form_tag event_user_events_path(@event, @user_event) do %>
            <%= text_field_tag :organizer, '', placeholder: 'NetID', :class => 'p-2' %>
            <%= submit_tag 'Add Organizer by NetID', :class => 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/import.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Events", events_path %></li>
  <li><%= link_to @event.title, event_attendance_entries_path(@event) %></li>
  <li>Import</li>
</ol>
<h1>Import Event Attendees</h1>

<%= simple_form_for @event, url: url_for(:action => 'import_lookup', :controller => 'events'), method: :post do |f| %>
  <div class="col-md-6">
    <%= f.input :import_list, as: :text, label: "Event Attendees To Import", hint: "You can include a list of unique identifiers (netid, yale email, upi, card-swipe number, or prox number). Each entry should be on a new line (press enter between each one). This will add attendees to your list, anyone already added will not be modified. Everyone uploaded will not be checked in yet, until they swipe their card." %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/new.html.erb
<br/>
<div class = "text-center">
  <h1>Create Event</h1>
</div>
<div class = "container">
  <%= render 'form' %>
</div>

app/views/events/registration.html.erb
<% if flash[:success].present? %>
  <p class="flash-success"><%= flash[:success] %></p>
<% elsif flash[:error].present? %>
  <p class="flash-error"><%= flash[:error] %></p>
<% end %>

<div class="row">
  <%= button_to 'Back to Dashboard', root_path, method: :get, :class => 'button-block' %>
  <br>
  <div class="card-container">
    <div class="card">
      <div class="title">
        <b><%=@event.title%> Check-in Page</b>
      </div>

      <div class="search-container">
        <div class="text-container">
          <p><%=@event.description%></p>

          <p><b>Card Swipe</b> or <b>Card Tap</b> or <b>NetID</b> or <b>Yale Email</b></p>
        </div>

        <%= form_tag check_in_event_path do %>
          <%= text_field_tag :prox_number, '', autofocus: true, :class => 'text-box' %>
          <%= submit_tag 'Check In', :class => 'button-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<%= button_to 'Back to Events', dashboard_path, method: :get, :class => 'btn btn-secondary' %>
<br />
<div class="row">
  <div class="col-xl-6 offset-xl-3 col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-12">
    <div class="container p-1">
    <%= render 'flashes' %>
    </div>
    <div class="card shadow text-center">
      <div class="card-header text-white bg-yale">
        <h2 class = "display-3"><b>Check in for <%=@event.title%></b></h2>
      </div>
      <div class="card-body">
        <p class="h3 m-1"><%=@event.description%></p>
        <br />
        <div class="h3 m-1">
          <p><b>Card Swipe</b> or <b>Card Tap</b> or <b>NetID</b></p>
        </div>
        <%= form_tag event_attendances_path(@event), id: 'swipr_swipe_form' do %>
          <div class="col-12 mx-auto input-group">
            <%= text_field_tag :search_param, '', autofocus: true, :class => 'p-2 form-control m-1' %>
            <%= submit_tag 'Check In', :class => 'btn btn-primary' %>
          </div>
        <% end %>
        <br />
        <p><%= @event.attendances.size %> Recorded</p>
        <% if @event.preregistration %>
          <p><%= @event.preregistrations.size %> Not yet checked in</p>
        <% end %>
      </div>
    </div>
  </div>
</div>