config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :attendances
    resources :events
    resources :user_events
    resources :preregistrations

    root to: 'users#index'
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # HighVoltage
  get '/dashboard' => 'dashboards#index', id: 'dashboard'
  get '/pages/user_manual' => 'pages#user_manual'

  resources :users, only: %i(edit update)
  resources :events, only: %i(new create show edit update destroy) do
    resources :attendances, only: %i(create index destroy) do
      collection do
        get 'export'
      end
    end
    resources :user_events, only: %i(create destroy)
    resources :preregistrations, only: %i(index new create destroy) do
      collection { post 'import' }
    end
  end
  resources :lookups, only: %i(index create)

  get '/heartbeat' => 'heartbeat#show'
  get '/heartbeat/api' => 'heartbeat#api'

  root to: 'pages#home', id: 'home'
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

# Controller for dashboard
class DashboardsController < ApplicationController
  before_action :set_events, only: [:index]

  def index; end

  private

  def set_events
    @events = current_user.events
                          .page(params[:page])
                          .per(5)
                          .order(created_at: :desc)
  end

  def authorize!; end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

# Dashboard helper class
module DashboardHelper
end

app/views/dashboards/events.html.erb
<h1>Dashboard</h1>

<%= button_to 'Create New Event', root_path, method: :get, :class => 'btn btn-primary btn-lg btn-block' %>

<div class="events-table">
<table id="events" aria-label="Events Table">
  <thead>
    <tr>
      <th>Event Name</th>
      <th>Attendee Count</th>
      <th>Last Use</th>
    </tr>
  </thead>

  <tbody>
    <% @user_events.each do |user_event| %>
      <tr>
        <td class="dash-buttons">
          <%= button_to 'Event Check-in', root_path, method: :get, :class => 'btn btn-primary btn-lg btn-block' %>
          <%= button_to 'Attendee List', event_attendances_path(user_event.event_id), method: :get, :class => 'btn btn-primary btn-lg btn-block' %>
        </td>
        <td>
          <%= user_event.event.title %>
        </td>
        <td>
          XXX
        </td>
        <td>
          <%= user_event.event.updated_at %>
        </td>
        <td>
          <%= button_to 'Edit Event', edit_event_path(user_event.event_id), method: :get, :class => 'btn btn-primary btn-lg btn-block' %>
          <%= button_to 'Delete Event', event_path(user_event.event_id), method: :delete, :class => 'btn btn-primary btn-lg btn-block' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/dashboards/index.html.erb
<div class="container">
  <h1>Events</h1>
</div>

<div class="container">
  <% if @events.any? %>
    <table  class="dashboard-table table-borderless mb-3" id="events" tabindex="0">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col">Title</th>
          <th scope="col">Attendee Count</th>
          <th scope="col">Last Use</th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>

      <tbody>
        <% @events.each do |event| %>
          <tr id="event row">
            <td>
              <%= button_to 'Event Check-in', event_path(event.id), method: :get, :class => 'btn btn-yale' %>
            </td>
            <td>
              <%= button_to 'Attendance Info', event_attendances_path(event.id), method: :get, :class => 'btn btn-primary ' %>
            </td>
            <td>
              <%= event.title %>
            </td>
            <td>
              <%= event.attendances.size %>
            </td>
            <td>
              <%= event.updated_at.strftime('%Y-%m-%d %I:%M %p') %>
            </td>
            <td>
              <%= button_to 'Edit Event', edit_event_path(event.id), method: :get, :class => 'btn btn-primary' %>
            </td>
            <td>
              <%= button_to 'X', event_path(event.id), method: :delete, data: { confirm: 'Are you sure? This action cannot be undone.'}, :class => 'btn btn-danger btn-sm', aria: { label: 'Delete Event' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class='d-flex justify-content-center'><%= paginate(@events) %></div>
  <% else %>
    <div class='d-flex justify-content-center'><h2>No events!</h2></div>
  <% end %>
</div>